Repository ComicScrip/lyon-react-mars22-p2g1, pull requests merged in 2022-04, with the labels that each got.

#22 initialization of Routes
  .eslintrc.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.js
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Main.jsx
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/BookDetail.jsx
  src/pages/BoxDetail.jsx
  src/pages/Form.jsx
  src/pages/Home.jsx
  src/pages/MyProfile.jsx
  src/pages/Search.jsx
Labels: Ready for prod

#63 Box list & book list Home
  package-lock.json
  package.json
  public/icons/book-alt.resized.png
  src/App.css
  src/components/Home_BookSelection.jsx
  src/components/Home_BoxList.jsx
  src/components/Main.jsx
  src/pages/BoxDetail.jsx
  src/pages/Home.jsx
  src/ressources/coordsBAL.json
  src/ressources/livresDB.json
  tailwind.config.js
Labels: Fixed - Ready for prod

#57 Navbar
  public/index.html
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/BAL-medium.png
  src/assets/check.png
  src/assets/form_logo.png
  src/assets/home_logo.png
  src/assets/map-navigation.png
  src/assets/search_logo.png
  src/assets/trash.png
  src/assets/user_logo.png
  src/components/Header.jsx
  src/components/Home_BookSelection.jsx
  src/components/NavBar.jsx
  src/components/PopupDisplayHome.jsx
  src/components/PopupHome.jsx
  src/index.css
  src/index.js
  src/pages/Home.jsx
  src/reportWebVitals.js
  src/ressources/coordsBAL.json
  src/ressources/livresDB.json
  src/setupTests.js
  src/styles/App.css
  src/styles/NavBar.css
  src/styles/Popup.css
  src/styles/PopupDisplay.css
  src/styles/index.css
Labels: Ready for prod

#76 Form
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/books.jpg
  src/components/FormComponent.jsx
  src/components/HomeBookSelection.jsx
  src/components/HomeBoxList.jsx
  src/components/Main.jsx
  src/components/NavBar.jsx
  src/components/PopupDisplayHome.jsx
  src/pages/Form.jsx
  src/pages/Home.jsx
  src/styles/FormComponent.css
  src/styles/HomeLists.css
  src/styles/Main.css
  src/styles/NavBar.css
  src/styles/Popup.css
  src/styles/index.css
Labels: Ready for prod

#82 popup BAL
  src/styles/Popup.css
Labels: WIP

#77 Contact component
  src/assets/adrien.png
  src/assets/clement.png
  src/assets/gaspard.png
  src/assets/pierre.png
  src/assets/woman.png
  src/components/ContactComponent.jsx
  src/pages/Form.jsx
  src/styles/Avatars.css
Labels: Fixed - Ready for prod

#60 Map initialisation
  img/Pins.png
  package-lock.json
  package.json
  public/index.html
  src/components/Mapmodule.jsx
  src/pages/Home.jsx
  src/ressources/coordsBAL.json
  src/styles/Main.css
  src/styles/Map.css
Labels: Fixed - Ready for prod

#80 Home lists style
  src/assets/box_closeempty.png
  src/assets/box_full.png
  src/assets/box_middle.png
  src/assets/box_middlefull.png
  src/assets/vintage.jpg
  src/components/ContactComponent.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/HomeBookSelection.jsx
  src/components/HomeBoxList.jsx
  src/components/PopupDisplayHome.jsx
  src/styles/App.css
  src/styles/HomeLists.css
  src/styles/Main.css
  src/styles/Map.css
  src/styles/NavBar.css
Labels: Fixed - Ready for prod

#96 Toast user action
  package-lock.json
  package.json
  src/components/AddBookForm.jsx
  src/components/Book.jsx
  src/components/BoxHeaders.jsx
  src/components/FormComponent.jsx
  src/components/Popup.jsx
  src/pages/BoxDetail.jsx
  src/styles/HomeLists.css
  src/styles/box_detail.css
Labels: Ready for prod

#97 Page détail livre : Mise en page (sauf bouton vérifier disponibilité)
  .eslintrc.json
  src/components/Book.jsx
  src/components/Header.jsx
  src/components/HomeBoxList.jsx
  src/components/Main.jsx
  src/components/ratingStar.jsx
  src/pages/BookDetail.jsx
  src/pages/BoxDetail.jsx
  src/pages/Home.jsx
  src/styles/App.css
  src/styles/Main.css
  src/styles/bookDetail.css
Labels: Ready for validation

#102 Link map to boxlist, add markers, all linked to API
  postcss.config.js
  src/components/Book.jsx
  src/components/BoxHeaders.jsx
  src/components/HomeBoxList.jsx
  src/components/Mapmodule.jsx
  src/components/PopupDisplayHome.jsx
  src/components/PopupMap.jsx
  src/pages/BoxDetail.jsx
  src/pages/Home.jsx
  src/ressources/coordsBAL.json
  src/styles/Map.css
  src/styles/PopUpMap.css
Labels: Ready for prod
